### ISSUE TITLE
issue - maybe when not finding the test name

### ISSUE THREAD

**Issue by bermud** [opengeospatial/teamengine-statistics#2]
When running:
java AdminLogCreator "Web Map Service (WMS) - 1.3.0" /Users/lbermudez/te-build/catalina_base/TE_BASE/users

I get the following error:

```
Exception in thread "main" java.lang.NullPointerException
    at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
    at java.util.Arrays.sort(Arrays.java:472)
    at AdminLogCreator.processForExecutions(AdminLogCreator.java:47)
    at AdminLogCreator.main(AdminLogCreator.java:182)
```

**Comment by upendra-sachan** [comment]
https://github.com/opengeospatial/teamengine-statistics/commit/08a5fa3dba4bf59e9fe4bec0a666a6a0beeefe5f
